# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ggg/xx/game-of-life

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ggg/xx/game-of-life

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ggg/xx/game-of-life/CMakeFiles /home/ggg/xx/game-of-life/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ggg/xx/game-of-life/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_of_life

# Build rule for target.
game_of_life: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_of_life
.PHONY : game_of_life

# fast build rule for target.
game_of_life/fast:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/build
.PHONY : game_of_life/fast

#=============================================================================
# Target rules for targets named gol_test

# Build rule for target.
gol_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gol_test
.PHONY : gol_test

# fast build rule for target.
gol_test/fast:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/build
.PHONY : gol_test/fast

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/Model.cpp.o
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/Model.cpp.i
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/Model.cpp.s
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life.dir/build.make CMakeFiles/game_of_life.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/HelloTest.o: test/HelloTest.cpp.o

.PHONY : test/HelloTest.o

# target to build an object file
test/HelloTest.cpp.o:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/HelloTest.cpp.o
.PHONY : test/HelloTest.cpp.o

test/HelloTest.i: test/HelloTest.cpp.i

.PHONY : test/HelloTest.i

# target to preprocess a source file
test/HelloTest.cpp.i:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/HelloTest.cpp.i
.PHONY : test/HelloTest.cpp.i

test/HelloTest.s: test/HelloTest.cpp.s

.PHONY : test/HelloTest.s

# target to generate assembly for a file
test/HelloTest.cpp.s:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/HelloTest.cpp.s
.PHONY : test/HelloTest.cpp.s

test/TestRunner.o: test/TestRunner.cpp.o

.PHONY : test/TestRunner.o

# target to build an object file
test/TestRunner.cpp.o:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestRunner.cpp.o
.PHONY : test/TestRunner.cpp.o

test/TestRunner.i: test/TestRunner.cpp.i

.PHONY : test/TestRunner.i

# target to preprocess a source file
test/TestRunner.cpp.i:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestRunner.cpp.i
.PHONY : test/TestRunner.cpp.i

test/TestRunner.s: test/TestRunner.cpp.s

.PHONY : test/TestRunner.s

# target to generate assembly for a file
test/TestRunner.cpp.s:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestRunner.cpp.s
.PHONY : test/TestRunner.cpp.s

test/TestgetNeighbor.o: test/TestgetNeighbor.cpp.o

.PHONY : test/TestgetNeighbor.o

# target to build an object file
test/TestgetNeighbor.cpp.o:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestgetNeighbor.cpp.o
.PHONY : test/TestgetNeighbor.cpp.o

test/TestgetNeighbor.i: test/TestgetNeighbor.cpp.i

.PHONY : test/TestgetNeighbor.i

# target to preprocess a source file
test/TestgetNeighbor.cpp.i:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestgetNeighbor.cpp.i
.PHONY : test/TestgetNeighbor.cpp.i

test/TestgetNeighbor.s: test/TestgetNeighbor.cpp.s

.PHONY : test/TestgetNeighbor.s

# target to generate assembly for a file
test/TestgetNeighbor.cpp.s:
	$(MAKE) -f CMakeFiles/gol_test.dir/build.make CMakeFiles/gol_test.dir/test/TestgetNeighbor.cpp.s
.PHONY : test/TestgetNeighbor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... game_of_life"
	@echo "... edit_cache"
	@echo "... gol_test"
	@echo "... rebuild_cache"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/HelloTest.o"
	@echo "... test/HelloTest.i"
	@echo "... test/HelloTest.s"
	@echo "... test/TestRunner.o"
	@echo "... test/TestRunner.i"
	@echo "... test/TestRunner.s"
	@echo "... test/TestgetNeighbor.o"
	@echo "... test/TestgetNeighbor.i"
	@echo "... test/TestgetNeighbor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

